---
-
  hosts: webservers
  become: yes
  tasks:
    - name: update and upgarde
      shell: apt update && apt upgrade -y
    - name: install Java
      shell: apt install default-jdk -y
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    - name: File for docker -compose
      shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
    - name: Remove docker containers if present
      shell: docker-compose down       
    - name: Run docker compose
      shell: docker-compose up -d
    - name: Enable firewall
      shell: echo "yes" | ufw enable
    - name: Enable port 8086 | openssh | 22
      shell: ufw allow 8086 && ufw allow 22 && ufw allow openssh
...
